import Head from 'next/head';
import Template from 'components/templates/Template';

const Home = () => {
  return (
    <Template>
      <Head>
        <title>Main page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <p>Main Page</p>
    </Template>
  );
};

export default Home;
