import { getAllProjects } from 'services/projects';
import Head from 'next/head';
import Template from 'components/templates/Template';

export const getStaticProps = () => {
  const projects = getAllProjects();

  return { props: { projects } };
};

const Portfolio = ({ projects }) => {
  return (
    <Template>
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Portfolio</h1>

      {projects.map((project) => (
        <div>
          <hr />
          <div>{project.cover}</div>
          <h2>{project.title}</h2>
          <p>{project.description}</p>
          <p>{project.date}</p>
          <ul>
            {project.tags.map((tag) => (
              <li>#{tag}</li>
            ))}
          </ul>
        </div>
      ))}
    </Template>
  );
};

export default Portfolio;
