import Head from 'next/head';
import Template from 'components/templates/Template';

const Portfolio = () => {
  return (
    <Template>
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <p>Portfolio</p>
    </Template>
  );
};

export default Portfolio;
